const SharkList = [
    { name: "African angelshark", media: 'https://media1.britannica.com/eb-media/88/161088-004-832806DD.jpg' },
    { name: "African dwarf sawshark", media: 'http://media.ecoblog.it/n/nuo/nuovaspeciedisqualo2011.jpg' },
    { name: "African frilled shark", media: 'https://www.arkive.org/frilled-shark/chlamydoselachus-anguineus/image-G38906.html' },
    { name: "African lanternshark", media: 'http://3w9yz8ifp462cet4q2j4fjen-wpengine.netdna-ssl.com/wp-content/uploads/2016/07/African-Lanternshark.jpg' },
    { name: "African ribbontail catshark", media: 'http://www.biodiversityexplorer.org/chondrichthyes/images/eridacnis_sinuans_658w.jpg' },
    { name: "African sawtail catshark", media: 'http://www.nhptv.org/wild/images/Halaelurusnatalensis.jpg' },
    { name: "Angelshark", media: 'http://www.elasmodiver.com/Sharkive%20images/CommonAngelShark044.jpg' },
    { name: "Angular angelshark", media: 'http://www.elasmodiver.com/Sharkive%20images/Angular_Angelshark_007.jpg' },
    { name: "Angular roughshark", media: 'https://53744bf91d44b81762e0-fbbc959d4e21c00b07dbe9c75f9c0b63.ssl.cf3.rackcdn.com/media/16/16BD33A6-AB47-4252-8C3E-235567C462D0/Presentation.Large/Angular-rough-shark-swimming.jpg' },
    { name: "Antilles catshark", media: 'http://fishillust.com/files/attach/images/5461/461/005/3beeb517bd012beab663f1a4b0b883f4.jpg' },
    { name: "Arabian carpetshark", media: 'https://53744bf91d44b81762e0-fbbc959d4e21c00b07dbe9c75f9c0b63.ssl.cf3.rackcdn.com/media/80/80CD9644-3FB3-4E5E-99A1-5C9FB9012703/Presentation.Large/Arabian-carpetshark-lateral-view.jpg' },
    { name: "Arabian catshark", media: 'http://www.nhptv.org/wild/images/Scyliorhinusretifer.jpg' },
    { name: "Arabian smooth-hound", media: ' ' },
    { name: "Argentine angelshark", media: ' ' },
    { name: "Arrowhead dogfish", media: ' ' },
    { name: "Atlantic angel shark", media: ' ' },
    { name: "Atlantic sawtail catshark", media: ' ' },
    { name: "Atlantic sharpnose shark", media: 'http://marinebio.org/upload/Rhizoprionodon-terraenovae/1.jpg' },
    { name: "Atlantic weasel shark", media: ' ' },
    { name: "Australian angelshark", media: ' ' },
    { name: "Australian blackspotted catshark", media: ' ' },
    { name: "Australian blacktip shark", media: 'http://cdn2.arkive.org/media/A8/A8961806-D86D-442F-AB6D-A2EA127E1754/Presentation.Large/Blacktip-shark-in-shallow-water.jpg' },
    { name: "Australian grey smooth-hound", media: ' ' },
    { name: "Australian marbled catshark", media: 'http://cdn.supanet.net/upload/images/201206/australian-marbled-catshark-22481.jpg' },
    { name: "Australian reticulate swellshark", media: ' ' },
    { name: "Australian sawtail catshark", media: ' ' },
    { name: "Australian sharpnose shark", media: ' ' },
    { name: "Australian spotted catshark", media: ' ' },
    { name: "Australian swellshark", media: ' ' },
    { name: "Australian weasel shark", media: ' ' },
    { name: "Azores dogfish", media: ' ' },
    { name: "Bahamas sawshark", media: ' ' },
    { name: "Bali catshark", media: ' ' },
    { name: "Balloon shark", media: ' ' },
    { name: "Banded houndshark", media: ' ' },
    { name: "Banded sand catshark", media: ' ' },
    { name: "Banded wobbegong", media: 'http://cdn1.arkive.org/media/44/44B54E20-54FF-401D-B598-3FA5655EE5F7/Presentation.Large/Spotted-wobbegong-swimming.jpg' },
    { name: "Bartail spurdog", media: ' ' },
    { name: "Barbelthroat carpetshark", media: ' ' },
    { name: "Barbeled houndshark", media: ' ' },
    { name: "Bareskin dogfish", media: ' ' },
    { name: "Basking shark", media: ' ' },
    { name: "Beige catshark", media: ' ' },
    { name: "Bigeye houndshark", media: ' ' },
    { name: "Bigeye sand tiger", media: ' ' },
    { name: "Bigeye thresher shark", media: ' ' },
    { name: "Bighead catshark", media: ' ' },
    { name: "Bighead spurdog", media: ' ' },
    { name: "Bignose shark", media: ' ' },
    { name: "Bigeyed sixgill shark", media: ' ' },
    { name: "Birdbeak dogfish", media: ' ' },
    { name: "Blackbelly lanternshark", media: ' ' },
    { name: "Black dogfish", media: ' ' },
    { name: "Blackfin gulper shark", media: ' ' },
    { name: "Blackgill catshark", media: ' ' },
    { name: "Blackmouth catshark", media: ' ' },
    { name: "Blackmouth lanternshark", media: ' ' },
    { name: "Blacknose shark", media: ' ' },
    { name: "Black roughscale catshark", media: ' ' },
    { name: "Blackspot shark", media: ' ' },
    { name: "Blackspotted catshark", media: ' ' },
    { name: "Blackspotted smooth-hound", media: ' ' },
    { name: "Blacktail reef shark", media: ' ' },
    { name: "Blacktailed spurdog", media: ' ' },
    { name: "Blacktip reef shark", media: 'http://cdn1.arkive.org/media/74/7424B81D-BFA1-4E3D-8A73-3CF31FE3EE3B/Presentation.Large/Male-blacktip-reef-shark.jpg' },
    { name: "Blacktip sawtail catshark", media: ' ' },
    { name: "Blacktip shark", media: ' ' },
    { name: "Blacktip tope", media: ' ' },
    { name: "Black wonder catshark", media: ' ' },
    { name: "Blind shark", media: 'https://53744bf91d44b81762e0-fbbc959d4e21c00b07dbe9c75f9c0b63.ssl.cf3.rackcdn.com/media/09/0994B54E-4E82-4E7C-847D-EA7D797D30EA/Presentation.Large/Juvenile-blind-shark-face-detail.jpg' },
    { name: "Blotched catshark, two different species", media: ' ' },
    { name: "Blotchy swellshark", media: ' ' },
    { name: "Blue-eye lanternshark", media: ' ' },
    { name: "Bluegrey carpetshark", media: ' ' },
    { name: "Blue shark", media: ' ' },
    { name: "Bluntnose sixgill shark", media: ' ' },
    { name: "Blunt-nose spiny dogfish", media: ' ' },
    { name: "Blurred lanternshark", media: ' ' },
    { name: "Boa catshark", media: ' ' },
    { name: "Bonnethead shark", media: ' ' },
    { name: "Borneo broadfin shark", media: ' ' },
    { name: "Borneo shark", media: ' ' },
    { name: "Bramble shark", media: ' ' },
    { name: "Brazilian sharpnose shark", media: ' ' },
    { name: "Bristled lanternshark", media: '' },
    { name: "Bristly catshark", media: ' ' },
    { name: "Broadbanded lanternshark", media: ' ' },
    { name: "Broadfin sawtail catshark", media: ' ' },
    { name: "Broadfin shark", media: ' ' },
    { name: "Broadgill catshark", media: ' ' },
    { name: "Broadhead catshark", media: ' ' },
    { name: "Broadmouth catshark", media: ' ' },
    { name: "Broadnose catshark", media: ' ' },
    { name: "Broadnose sevengill shark", media: ' ' },
    { name: "Broad-snout lanternshark", media: ' ' },
    { name: "Brownbanded bamboo shark", media: ' ' },
    { name: "Brown catshark", media: 'http://www.fishbase.org/images/species/Apbru_u0.jpg' },
    { name: "Brown lanternshark", media: ' ' },
    { name: "Brown shyshark", media: ' ' },
    { name: "Brown smoothhound", media: ' ' },
    { name: "Brownspotted catshark", media: ' ' },
    { name: "Bull shark", media: ' ' },
    { name: "Burmese bamboo shark", media: ' ' },
    { name: "Campeche catshark", media: ' ' },
    { name: "Caribbean lanternshark", media: ' ' },
    { name: "Caribbean reef shark", media: ' ' },
    { name: "Caribbean roughshark", media: ' ' },
    { name: "Caribbean sharpnose shark", media: ' ' },
    { name: "Caribbean smooth-hound", media: ' ' },
    { name: "Carolina hammerhead", media: ' ' },
    { name: "Cenderawasih epaulette shark", media: ' ' },
    { name: "Chain catshark", media: ' ' },
    { name: "Chilean angelshark", media: ' ' },
    { name: "Chilean lanternshark", media: ' ' },
    { name: "Clouded angelshark", media: ' ' },
    { name: "Cloudy catshark", media: ' ' },
    { name: "Coates' shark", media: ' ' },
    { name: "Cobbler wobbegong", media: ' ' },
    { name: "Collared carpetshark", media: ' ' },
    { name: "Combtooth dogfish", media: ' ' },
    { name: "Combtooth lanternshark", media: ' ' },
    { name: "Common smooth-hound", media: ' ' },
    { name: "Comoro catshark", media: ' ' },
    { name: "Cook's swellshark", media: ' ' },
    { name: "Cookie-cutter shark", media: ' ' },
    { name: "Copper shark", media: ' ' },
    { name: "Coral catshark", media: ' ' },
    { name: "Creek whaler", media: ' ' },
    { name: "Crested bullhead shark", media: 'https://oceanuts.files.wordpress.com/2014/01/broadnose-sevengill-shark-portrait.jpg' },
    { name: "Crocodile shark", media: ' ' },
    { name: "Crying catshark", media: ' ' },
    { name: "Cryptic hornshark", media: ' ' },
    { name: "Cuban dogfish", media: ' ' },
    { name: "Cuban ribbontail catshark", media: ' ' },
    { name: "Cylindrical lanternshark", media: ' ' },
    { name: "Cyrano spurdog", media: ' ' },
    { name: "Daggernose shark", media: ' ' },
    { name: "Dark freckled catshark", media: ' ' },
    { name: "Dark shyshark", media: ' ' },
    { name: "Deepwater catshark", media: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Apristurus_profundorum.jpg/800px-Apristurus_profundorum.jpg' },
    { name: "Deepwater sicklefin houndshark", media: ' ' },
    { name: "Dense-scale lantern shark", media: ' ' },
    { name: "Disparate angelshark", media: ' ' },
    { name: "Draughtsboard shark", media: ' ' },
    { name: "Dumb gulper shark", media: ' ' },
    { name: "Dusky catshark", media: ' ' },
    { name: "Dusky shark", media: ' ' },
    { name: "Dusky smooth-hound", media: ' ' },
    { name: "Dusky snout catshark", media: ' ' },
    { name: "Dwarf catshark", media: ' ' },
    { name: "Dwarf catshark", media: ' ' },
    { name: "Dwarf false catshark", media: ' ' },
    { name: "Dwarf gulper shark", media: ' ' },
    { name: "Dwarf lanternshark", media: ' ' },
    { name: "Dwarf sawtail catshark", media: ' ' },
    { name: "Dwarf smooth-hound", media: ' ' },
    { name: "Dwarf spotted wobbegong", media: ' ' },
    { name: "Eastern angelshark", media: ' ' },
    { name: "Eastern banded catshark", media: ' ' },
    { name: "Eastern highfin spurdog", media: ' ' },
    { name: "Eastern longnose spurdog", media: ' ' },
    { name: "Eastern spotted gummy shark", media: ' ' },
    { name: "Edmund's spurdog", media: ' ' },
    { name: "Elongate carpetshark", media: ' ' },
    { name: "Epaulette shark", media: ' ' },
    { name: "False catshark", media: ' ' },
    { name: "False lanternshark", media: ' ' },
    { name: "False smalltail shark", media: ' ' },
    { name: "Fat catshark", media: ' ' },
    { name: "Fatspine spurdog", media: ' ' },
    { name: "Fedorov's catshark", media: ' ' },
    { name: "Filetail catshark", media: ' ' },
    { name: "Finetooth shark", media: ' ' },
    { name: "Flaccid catshark", media: ' ' },
    { name: "Flagtail swellshark", media: ' ' },
    { name: "Flapnose houndshark", media: ' ' },
    { name: "Flathead catshark", media: ' ' },
    { name: "Floral banded wobbegong", media: ' ' },
    { name: "Formosa swellshark", media: ' ' },
    { name: "Freckled catshark", media: ' ' },
    { name: "Frilled shark", media: ' ' },
    { name: "Fringefin lanternshark", media: '' },
    { name: "Frog shark", media: ' ' },
    { name: "Galapagos bullhead shark", media: ' ' },
    { name: "Galapagos shark", media: ' ' },
    { name: "Galápagos catshark", media: 'https://i.pinimg.com/736x/4b/f5/50/4bf550414c1a7f578ecf56e8c24d25cd--marine-fish-coral.jpg' },
    { name: "Galbraith's catshark", media: ' ' },
    { name: "Ganges shark", media: ' ' },
    { name: "Garrick's catshark", media: ' ' },
    { name: "Gecko catshark", media: ' ' },
    { name: "Ghost catshark", media: ' ' },
    { name: "Ginger carpetshark", media: ' ' },
    { name: "Goblin shark", media: ' ' },
    { name: "Graceful catshark", media: ' ' },
    { name: "Graceful shark", media: ' ' },
    { name: "Granular dogfish", media: ' ' },
    { name: "Great hammerhead", media: ' ' },
    { name: "Great lanternshark", media: ' ' },
    { name: "Great white shark", media: ' ' },
    { name: "Green-eye spurdog", media: ' ' },
    { name: "Green lanternshark", media: ' ' },
    { name: "Greenland shark", media: ' ' },
    { name: "Grey bamboo shark", media: ' ' },
    { name: "Grey sharpnose shark", media: ' ' },
    { name: "Grey smooth-hound", media: 'http://cdn2.arkive.org/media/C4/C45BC522-8A2B-416E-A8AD-7478111A1233/Presentation.Large/Humpback-smoothhound-specimen.jpg' },
    { name: "Grinning catshark", media: ' ' },
    { name: "Guadalupe lanternshark", media: ' ' },
    { name: "Gulf catshark", media: ' ' },
    { name: "Gulf of Mexico filetail catshark", media: ' ' },
    { name: "Gulf smooth-hound", media: 'http://cdn2.arkive.org/media/B4/B4CBFDC3-9DDA-40B9-96F7-8A2D34832515/Presentation.Large/Gulf-of-Mexico-smoothhound-lateral-view.jpg' },
    { name: "Gulper shark", media: 'http://cdn1.arkive.org/media/42/42FFA228-04A9-4841-9042-C8A70C567BA1/Presentation.Large/Gulper-shark-swimming.jpg' },
    { name: "Gummy shark", media: ' ' },
    { name: "Halmahera epaulette shark", media: ' ' },
    { name: "Hardnose shark", media: ' ' },
    { name: "Harlequin catshark", media: ' ' },
    { name: "Hasselt's bamboo shark", media: ' ' },
    { name: "Hawaiian lanternshark", media: ' ' },
    { name: "Hidden angelshark", media: ' ' },
    { name: "Highfin dogfish", media: ' ' },
    { name: "Hoary catshark", media: ' ' },
    { name: "Honeycomb Izak", media: ' ' },
    { name: "Hooded carpetshark", media: ' ' },
    { name: "Hooktooth dogfish", media: ' ' },
    { name: "Hooktooth shark", media: ' ' },
    { name: "Horn shark", media: ' ' },
    { name: "Human's whaler shark", media: ' ' },
    { name: "Humpback catshark", media: ' ' },
    { name: "Humpback smooth-hound", media: ' ' },
    { name: "Iceland catshark", media: ' ' },
    { name: "Indian swellshark", media: ' ' },
    { name: "Indonesian angelshark", media: ' ' },
    { name: "Indonesian filetail catshark", media: ' ' },
    { name: "Indonesian greeneye spurdog", media: ' ' },
    { name: "Indonesian houndshark", media: ' ' },
    { name: "Indonesian shortsnout spurdog", media: ' ' },
    { name: "Indonesian speckled carpetshark", media: ' ' },
    { name: "Indonesian speckled catshark", media: ' ' },
    { name: "Indonesian whaler shark", media: ' ' },
    { name: "Indonesian wobbegong", media: ' ' },
    { name: "Izak catshark", media: ' ' },
    { name: "Izu catshark", media: ' ' },
    { name: "Japanese angelshark", media: ' ' },
    { name: "Japanese bullhead shark", media: ' ' },
    { name: "Japanese catshark", media: ' ' },
    { name: "Japanese roughshark", media: ' ' },
    { name: "Japanese sawshark", media: ' ' },
    { name: "Japanese shortnose spurdog", media: ' ' },
    { name: "Japanese spurdog", media: ' ' },
    { name: "Japanese topeshark", media: ' ' },
    { name: "Japanese velvet dogfish", media: ' ' },
    { name: "Japanese wobbegong", media: ' ' },
    { name: "Kermadec smooth hound", media: ' ' },
    { name: "Kermadec spiny dogfish", media: ' ' },
    { name: "Kitefin shark", media: ' ' },
    { name: "Knifetooth dogfish", media: ' ' },
    { name: "Lana's sawshark", media: ' ' },
    { name: "Largenose catshark", media: ' ' },
    { name: "Largespine velvet dogfish", media: ' ' },
    { name: "Largetooth cookiecutter shark", media: 'https://www.advancedaquarist.com/blog/when-cookiecutter-sharks-attack/image' },
    { name: "Leafscale gulper shark", media: ' ' },
    { name: "Lemon shark", media: ' ' },
    { name: "Leopard catshark", media: ' ' },
    { name: "Leopard epaulette shark", media: ' ' },
    { name: "Leopard shark", media: 'http://cdn2.arkive.org/media/84/84C2E971-0D85-40AA-8FD0-E1ECD9BA5B0E/Presentation.Large/Leopard-shark-lateral-view.jpg' },
    { name: "Lined catshark", media: ' ' },
    { name: "Lined lanternshark", media: ' ' },
    { name: "Lined lanternshark", media: ' ' },
    { name: "Little gulper shark", media: ' ' },
    { name: "Little sleeper shark", media: ' ' },
    { name: "Lizard catshark", media: ' ' },
    { name: "Lollipop catshark", media: ' ' },
    { name: "Lombok highfin spurdog", media: ' ' },
    { name: "Longfin catshark", media: ' ' },
    { name: "Longfin mako", media: ' ' },
    { name: "Longfin sawtail catshark", media: ' ' },
    { name: "Longhead catshark", media: ' ' },
    { name: "Longnose catshark", media: ' ' },
    { name: "Longnose houndshark", media: ' ' },
    { name: "Longnose pygmy shark", media: ' ' },
    { name: "Longnose sawshark", media: ' ' },
    { name: "Longnose sawtail catshark", media: ' ' },
    { name: "Longnose spurdog", media: ' ' },
    { name: "Longnose velvet dogfish", media: ' ' },
    { name: "Longsnout dogfish", media: ' ' },
    { name: "Longnose sleeper shark", media: ' ' },
    { name: "Lowfin gulper shark", media: 'http://media-cache-ak0.pinimg.com/736x/b4/ed/99/b4ed990e76e0c30b4de1ad3830fdf1d1.jpg' },
    { name: "Magnificent catshark", media: ' ' },
    { name: "Mandarin dogfish", media: ' ' },
    { name: "Mangalore houndshark", media: ' ' },
    { name: "McMillan's catshark", media: 'http://www.fishbase.org/images/species/Paalb_m1.jpg' },
    { name: "Megamouth shark", media: 'http://s.newsweek.com/sites/www.newsweek.com/files/styles/lg/public/2017/07/27/megamouth-shark.jpg' },
    { name: "Mexican angelshark", media: ' ' },
    { name: "Mexican hornshark", media: ' ' },
    { name: "Milk-eye catshark", media: ' ' },
    { name: "Milk shark", media: 'http://fishesofaustralia.net.au/Images/Image/RhizoprionodonAcutusCSIRO.jpg' },
    { name: "Mini gulper shark", media: ' ' },
    { name: "Moller's lanternshark", media: ' ' },
    { name: "Mosaic gulper shark", media: ' ' },
    { name: "Mouse catshark", media: 'http://cdn2.arkive.org/media/A7/A7D5B008-79FE-4C59-9984-5CA7B1F71091/Presentation.Large/Striped-catfish-caught-in-anemone.jpg' },
    { name: "Mud catshark", media: ' ' },
    { name: "Mukah river shark", media: ' ' },
    { name: "Narrowbar swellshark", media: ' ' },
    { name: "Narrowfin smooth-hound", media: ' ' },
    { name: "Narrowhead catshark", media: ' ' },
    { name: "Narrowmouthed catshark", media: ' ' },
    { name: "Narrownose smooth-hound", media: ' ' },
    { name: "Narrowtail catshark", media: ' ' },
    { name: "Natal shyshark", media: ' ' },
    { name: "Necklace carpetshark", media: ' ' },
    { name: "Nervous shark", media: ' ' },
    { name: "Network wobbegong", media: ' ' },
    { name: "New Caledonia catshark", media: ' ' },
    { name: "New Zealand catshark", media: ' ' },
    { name: "New Zealand lanternshark", media: ' ' },
    { name: "Night shark", media: ' ' },
    { name: "Ninja lanternshark", media: ' ' },
    { name: "Northern river shark", media: ' ' },
    { name: "Northern sawtail catshark", media: ' ' },
    { name: "Northern spiny dogfish", media: ' ' },
    { name: "Northern wobbegong", media: ' ' },
    { name: "Nurse shark", media: ' ' },
    { name: "Nursehound", media: ' ' },
    { name: "Oakley's catshark", media: ' ' },
    { name: "Oceanic whitetip shark", media: ' ' },
    { name: "Ocellate topeshark", media: ' ' },
    { name: "Ocellated angelshark", media: ' ' },
    { name: "Oman bullhead shark", media: ' ' },
    { name: "Onefin catshark", media: ' ' },
    { name: "Orange spotted catshark", media: ' ' },
    { name: "Ornate angelshark", media: ' ' },
    { name: "Ornate dogfish", media: ' ' },
    { name: "Ornate wobbegong", media: ' ' },
    { name: "Pacific angelshark", media: ' ' },
    { name: "Pacific nurse shark", media: ' ' },
    { name: "Pacific sharpnose shark", media: 'http://cdn1.arkive.org/media/7A/7A7EBF49-8ABE-4CAC-AF2D-E8B9FD1E7E41/Presentation.Large/Pacific-sharpnose-shark-caught-on-a-shark-fishing-longline.jpg' },
    { name: "Pacific sleeper shark", media: ' ' },
    { name: "Pacific smalltail shark", media: ' ' },
    { name: "Pacific spadenose shark", media: ' ' },
    { name: "Pacific spiny dogfish", media: ' ' },
    { name: "Painted swellshark", media: ' ' },
    { name: "Pale catshark", media: ' ' },
    { name: "Pale spotted catshark", media: ' ' },
    { name: "Panama ghost catshark", media: ' ' },
    { name: "Papua shorttail lanternshark", media: ' ' },
    { name: "Papuan epaulette shark", media: ' ' },
    { name: "Pelagic thresher shark", media: 'http://sharks.org/wp-content/uploads/2013/07/Pelagic-thresher.jpg' },
    { name: "Peppered catshark", media: ' ' },
    { name: "Phallic catshark", media: ' ' },
    { name: "Philippines angelshark", media: ' ' },
    { name: "Philippines ribbontail catshark", media: ' ' },
    { name: "Philippines swellshark", media: ' ' },
    { name: "Pigeye shark", media: ' ' },
    { name: "Pink lanternshark", media: ' ' },
    { name: "Pinocchio catshark", media: ' ' },
    { name: "Plunket's shark", media: ' ' },
    { name: "Pocket shark", media: ' ' },
    { name: "Pondicherry shark", media: ' ' },
    { name: "Porbeagle shark", media: ' ' },
    { name: "Port Jackson shark", media: ' ' },
    { name: "Portuguese dogfish", media: ' ' },
    { name: "Prickly dogfish", media: ' ' },
    { name: "Prickly shark", media: ' ' },
    { name: "Puffadder shyshark", media: 'http://www.nhptv.org/wild/images/Scyliorhinuscanicula.jpg' },
    { name: "Pygmy lanternshark", media: ' ' },
    { name: "Pygmy ribbontail catshark", media: ' ' },
    { name: "Pygmy shark", media: ' ' },
    { name: "Quagga catshark", media: ' ' },
    { name: "Rasptooth dogfish", media: ' ' },
    { name: "Redspotted catshark", media: ' ' },
    { name: "Reticulated swellshark", media: ' ' },
    { name: "Roughback catshark", media: ' ' },
    { name: "Rough longnose dogfish", media: ' ' },
    { name: "Roughskin catshark", media: ' ' },
    { name: "Roughskin dogfish", media: ' ' },
    { name: "Roughskin spurdog", media: ' ' },
    { name: "Roughtail catshark", media: ' ' },
    { name: "Rusty carpetshark", media: ' ' },
    { name: "Rusty catshark", media: ' ' },
    { name: "Saddle carpetshark", media: ' ' },
    { name: "Saddled swellshark", media: ' ' },
    { name: "Sailback houndshark", media: ' ' },
    { name: "Sailfin roughshark", media: 'http://sharkfactsforkids.weebly.com/uploads/1/8/6/9/18696762/1369603012.jpg' },
    { name: "Salamander shark", media: ' ' },
    { name: "Saldanha catshark", media: ' ' },
    { name: "Salmon shark", media: ' ' },
    { name: "Sandtiger shark", media: ' ' },
    { name: "Sandbar shark", media: 'http://cdn2.arkive.org/media/AD/AD9950DE-8A91-4EBA-8AA7-383F274A4A53/Presentation.Large/Sandbar-shark-swimming.jpg' },
    { name: "Sarawak pygmy swellshark", media: ' ' },
    { name: "Sarawak smooth-hound", media: ' ' },
    { name: "Sawback angelshark", media: ' ' },
    { name: "Scalloped bonnethead", media: ' ' },
    { name: "Scalloped hammerhead", media: ' ' },
    { name: "Scoophead", media: ' ' },
    { name: "Sculpted lanternshark", media: ' ' },
    { name: "Seychelles carpetshark", media: ' ' },
    { name: "Seychelles gulper shark", media: ' ' },
    { name: "Seychelles spurdog", media: ' ' },
    { name: "Sharpfin houndshark", media: ' ' },
    { name: "Sharpnose sevengill shark", media: ' ' },
    { name: "Sharptooth houndshark", media: ' ' },
    { name: "Sharptooth smooth-hound", media: ' ' },
    { name: "Sherwood dogfish", media: ' ' },
    { name: "Shortbelly catshark", media: 'http://www.fishbase.org/images/species/Apbre_m0.jpg' },
    { name: "Shortfin mako", media: ' ' },
    { name: "Shortfin smooth lanternshark", media: ' ' },
    { name: "Shortnose demon catshark", media: ' ' },
    { name: "Shortnose sawshark", media: ' ' },
    { name: "Shortnose spurdog", media: ' ' },
    { name: "Shortspine spurdog", media: 'http://cdn2.arkive.org/media/F3/F3D749BF-C188-4140-9E39-DE6C0F8BF137/Presentation.Large/Shortspine-spurdog-resting-on-reef.jpg' },
    { name: "Shorttail lanternshark", media: ' ' },
    { name: "Shorttail nurse shark", media: ' ' },
    { name: "Sicklefin houndshark", media: ' ' },
    { name: "Sicklefin lemon shark", media: ' ' },
    { name: "Sicklefin smooth-hound", media: ' ' },
    { name: "Sicklefin weasel shark", media: ' ' },
    { name: "Silky shark", media: ' ' },
    { name: "Silvertip shark", media: ' ' },
    { name: "Sixgill sawshark", media: ' ' },
    { name: "Slender bamboo shark", media: ' ' },
    { name: "Slender catshark", media: ' ' },
    { name: "Slender gulper shark", media: ' ' },
    { name: "Slender sawtail catshark", media: ' ' },
    { name: "Slender smooth-hound", media: ' ' },
    { name: "Slender weasel shark", media: ' ' },
    { name: "Sliteye shark", media: ' ' },
    { name: "Smallbelly catshark", media: ' ' },
    { name: "Smalldorsal catshark", media: ' ' },
    { name: "Smalleye catshark", media: ' ' },
    { name: "Smalleye hammerhead", media: ' ' },
    { name: "Smalleye lantern shark", media: ' ' },
    { name: "Smalleye pygmy shark", media: ' ' },
    { name: "Smalleye smooth-hound", media: ' ' },
    { name: "Smallfin catshark", media: ' ' },
    { name: "Smallfin gulper shark", media: ' ' },
    { name: "Small-spotted catshark", media: ' ' },
    { name: "Smalltail shark", media: ' ' },
    { name: "Smalltooth sand tiger", media: 'https://oceanuts.files.wordpress.com/2014/01/smalltooth-sand-tiger-shark.jpg' },
    { name: "Smoothback angelshark", media: '' },
    { name: "Smooth hammerhead", media: ' ' },
    { name: "Smooth lanternshark", media: ' ' },
    { name: "Smoothtooth blacktip shark", media: ' ' },
    { name: "Snaggletooth shark", media: ' ' },
    { name: "Sombre catshark", media: ' ' },
    { name: "South China catshark", media: 'http://www.nhptv.org/wild/images/Porodermapantherinum.jpg' },
    { name: "Southern dogfish", media: ' ' },
    { name: "Southern lanternshark", media: ' ' },
    { name: "Southern lollipop catshark", media: ' ' },
    { name: "Southern mandarin dogfish", media: ' ' },
    { name: "Southern sawtail catshark", media: ' ' },
    { name: "Southern sleeper shark", media: ' ' },
    { name: "Spadenose shark", media: ' ' },
    { name: "Sparsetooth dogfish", media: ' ' },
    { name: "Spatulasnout catshark", media: ' ' },
    { name: "Speartooth shark", media: ' ' },
    { name: "Speckled carpetshark", media: ' ' },
    { name: "Speckled catshark", media: ' ' },
    { name: "Speckled smooth-hound", media: 'http://www.discoverlife.org/IM/I_RR/0024/320/Mustelus_mento,I_RR2448.jpg' },
    { name: "Speckled swellshark", media: ' ' },
    { name: "Spined pygmy shark", media: ' ' },
    { name: "Spinner shark", media: 'http://r.ddmcdn.com/s_f/DSC/uploads/2014/07/north-america-spinner-shark-625x450.jpg' },
    { name: "Spiny dogfish", media: ' ' },
    { name: "Splendid lanternshark", media: ' ' },
    { name: "Spongehead catshark", media: ' ' },
    { name: "Spotless catshark", media: ' ' },
    { name: "Spotless smooth-hound", media: ' ' },
    { name: "Spottail shark", media: ' ' },
    { name: "Spotted-belly catshark", media: ' ' },
    { name: "Spotted estuary smooth-hound", media: ' ' },
    { name: "Spotted houndshark", media: ' ' },
    { name: "Spotted wobbegong", media: ' ' },
    { name: "Springer's sawtail catshark", media: ' ' },
    { name: "Starspotted smooth-hound", media: ' ' },
    { name: "Starry catshark", media: ' ' },
    { name: "Starry smooth-hound", media: ' ' },
    { name: "Steven's swellshark", media: ' ' },
    { name: "Straight-tooth weasel shark", media: ' ' },
    { name: "Striped catshark", media: ' ' },
    { name: "Striped smooth-hound", media: ' ' },
    { name: "Sulu gollumshark", media: ' ' },
    { name: "Swellshark", media: ' ' },
    { name: "Taillight shark", media: ' ' },
    { name: "Tailspot lanternshark", media: ' ' },
    { name: "Taiwan angelshark", media: ' ' },
    { name: "Taiwan saddled carpetshark", media: ' ' },
    { name: "Taiwan spurdog", media: ' ' },
    { name: "Tasselled wobbegong", media: ' ' },
    { name: "Tawny nurse shark", media: ' ' },
    { name: "Thorny lanternshark", media: ' ' },
    { name: "Thresher shark", media: ' ' },
    { name: "Tiger catshark", media: ' ' },
    { name: "Tiger shark", media: ' ' },
    { name: "Tope shark", media: ' ' },
    { name: "Triton epaulette shark", media: ' ' },
    { name: "Tropical sawshark", media: ' ' },
    { name: "Variegated catshark", media: ' ' },
    { name: "Velvet belly lanternshark", media: ' ' },
    { name: "Velvet catshark", media: ' ' },
    { name: "Velvet dogfish", media: ' ' },
    { name: "Viper dogfish", media: ' ' },
    { name: "West African catshark", media: ' ' },
    { name: "West Indian lanternshark", media: ' ' },
    { name: "Western angelshark", media: ' ' },
    { name: "Western gulper shark", media: ' ' },
    { name: "Western highfin spurdog", media: ' ' },
    { name: "Western longnose spurdog", media: ' ' },
    { name: "Western spotted catshark", media: ' ' },
    { name: "Western spotted gummy shark", media: ' ' },
    { name: "Western wobbegong", media: ' ' },
    { name: "Whale shark", media: ' ' },
    { name: "Whiskery shark", media: ' ' },
    { name: "Whitebodied catshark", media: ' ' },
    { name: "Whitecheek shark", media: ' ' },
    { name: "White-clasper catshark", media: ' ' },
    { name: "Whitefin dogfish", media: ' ' },
    { name: "White-fin smooth-hound", media: 'http://cdn2.arkive.org/media/99/99712D8C-D7B5-42AB-9439-F3C12F4C004C/Presentation.Large/Dusky-smoothhound-head-profile.jpg' },
    { name: "Whitefin swellshark", media: ' ' },
    { name: "Whitefin topeshark", media: ' ' },
    { name: "White ghost catshark", media: ' ' },
    { name: "White-margin fin smooth-hound", media: 'http://cdn2.arkive.org/media/C4/C47D7328-D4D9-49C2-9FDA-F9A3D39A6FC3/Presentation.Large/Dusky-smoothhound-swimming.jpg' },
    { name: "Whitemarked gollumshark", media: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Gollum_attenuatus_macauley1.jpg/1200px-Gollum_attenuatus_macauley1.jpg' },
    { name: "Whitenose shark", media: ' ' },
    { name: "Whitesaddled catshark", media: ' ' },
    { name: "Whitespotted bamboo shark", media: ' ' },
    { name: "Whitespotted bullhead shark", media: ' ' },
    { name: "Whitespotted catshark", media: ' ' },
    { name: "Whitespotted smooth-hound", media: ' ' },
    { name: "Whitetail dogfish", media: ' ' },
    { name: "White-tip catshark", media: ' ' },
    { name: "Whitetip reef shark", media: ' ' },
    { name: "Whitetip weasel shark", media: 'http://cdn2.arkive.org/media/D1/D1B9F4E8-172D-46C6-9150-6C2A6A8D6908/Presentation.Large/Basking-shark-dorsal-view.jpg' },
    { name: "Winghead shark", media: ' ' },
    { name: "Yellowspotted catshark", media: ' ' },
    { name: "Zebra bullhead shark", media: 'http://cdn2.arkive.org/media/F1/F19E65EA-B29D-45A3-ABCC-FF5C82953F3D/Presentation.Large/Galapagos-bullhead-shark.jpg' },
    { name: "Zebra shark", media: 'https://www.cantechletter.com/wp-content/uploads/2017/01/zebra_shark5-400x300.jpg' }
]

export default SharkList;